### ISSUE TITLE
`inline` compiles all images to white

### ISSUE THREAD

**Issue by iwein** [borodean/postcss-assets#5] opened 2015-01-09 15:19 UTC
We replaced url('…') with inline('…') and noticed that all images suddenly had the same (white) base64 encoded string. My expectation was that they would work similarly on the same path.

**Comment by borodean** [comment] 2015-01-11 19:08
I’m unable to reproduce it. Can we skype on this one, @iwein?

**Comment by iwein** [comment] 2015-01-13 06:51
Yeah sure, just ping me.

On Sun, Jan 11, 2015 at 8:08 PM, Vadim Borodean <notifications@github.com>
wrote:

> I’m unable to reproduce it. Can we skype on this one, @iwein
> <https://github.com/iwein>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borodean/postcss-assets/issues/5#issuecomment-69506438>
> .
>



-- 
Hire StarterSquad.com <http://www.startersquad.com/> to bring your ideas to
life.

**Comment by borodean** [comment] 2015-02-06 18:00
Fixed by replacing a way to Base64 encode https://github.com/borodean/postcss-assets/releases/tag/1.1.3

**Closed by borodean** 2015-02-06 18:00 UTC
Labels: bug
